from webapp.models.testers.swindle_auth_tester import SwindleAuthTester
from webapp.models.testers.github_auth_tester import GithubAuthTester
from webapp.models.testers.trello_auth_tester import TrelloAuthTester
from webapp.models.testers.linkedin_auth_tester import LinkedinAuthTester
from webapp.models.testers.facebook_auth_tester import FacebookAuthTester